export const HANDLE_PRODUCTDETAIL = 'HANDLE_PRODUCTDETAIL';
export const HANDLE_ISOPENDETAILMODAL = 'HANDLE_ISOPENDETAILMODAL';
export const HANDLE_ISOPENCARTMODAL = 'HANDLE_ISOPENCARTMODAL';
export const HANDLE_ADDTOCART = 'HANDLE_ADDTOCART';
export const HANDLE_DELETECART = 'HANDLE_DELETECART';
export const HANDLE_EDITQTYCART = 'HANDLE_EDITQTYCART';